/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import database.UserMYSQLConnection;
import model.UserModel;

import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Frouen Junior
 */
public class ManageAccounts extends javax.swing.JFrame {

    DefaultTableModel userTableModel;
    List<UserModel> userList;
    /**
     * Creates new form ManageAccounts
     */
    public ManageAccounts() {
        initComponents();

        String [] columnNames = {"ID", "Username", "Password", "Role"};
        userTableModel = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(userTableModel);
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Password", "Role"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Create new account");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Back to Main Menu");
        jButton4.setActionCommand("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Options");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("MANAGE ACCOUNTS");

        jButton2.setText("Delete");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.setActionCommand("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // This is for creating account
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CreateAccount();
    }//GEN-LAST:event_jButton1ActionPerformed

    // This is for the back to menu admin
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminMainMenu adminmenu = new AdminMainMenu();
        adminmenu.setVisible(true);
        adminmenu.setLocationRelativeTo(null);
        this.dispose(); // Close the current window
    }//GEN-LAST:event_jButton4ActionPerformed

    // This is for the delete user
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DeleteAccount();
    }//GEN-LAST:event_jButton2ActionPerformed

    // This si for edit the user
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       editAccount();
    }//GEN-LAST:event_jButton3ActionPerformed


    void CreateAccount(){
        // Create a panel to hold input fields
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.GridLayout(0, 2, 5, 5)); // Grid layout for labels and fields

// Add input fields
        panel.add(new javax.swing.JLabel("Last Name:"));
        javax.swing.JTextField lastNameField = new javax.swing.JTextField();
        panel.add(lastNameField);

        panel.add(new javax.swing.JLabel("First Name:"));
        javax.swing.JTextField firstNameField = new javax.swing.JTextField();
        panel.add(firstNameField);

        panel.add(new javax.swing.JLabel("Middle Name:"));
        javax.swing.JTextField middleNameField = new javax.swing.JTextField();
        panel.add(middleNameField);

        panel.add(new javax.swing.JLabel("Contact Number:"));
        javax.swing.JTextField contactField = new javax.swing.JTextField();
        panel.add(contactField);


        panel.add(new javax.swing.JLabel("Address"));
        javax.swing.JTextField addressField = new javax.swing.JTextField();
        panel.add(addressField);

        panel.add(new javax.swing.JLabel("Username"));
        javax.swing.JTextField usernameField = new javax.swing.JTextField();
        panel.add(usernameField);

        panel.add(new javax.swing.JLabel("Password"));
        javax.swing.JPasswordField passwordField = new javax.swing.JPasswordField();
        panel.add(passwordField);

        panel.add(new javax.swing.JLabel("Confirm Password"));
        javax.swing.JPasswordField confirmpasswordField = new javax.swing.JPasswordField();
        panel.add(confirmpasswordField);

        panel.add(new javax.swing.JLabel("Role"));
        javax.swing.JComboBox<String> roleComboBox = new javax.swing.JComboBox<>(new String[]{"Admin", "User"});
        panel.add(roleComboBox);

    // Custom button options
        Object[] options = {"Submit", "Cancel"};

    // Wrap JOptionPane in a JDialog
        javax.swing.JOptionPane optionPane = new javax.swing.JOptionPane(
                panel,
                javax.swing.JOptionPane.PLAIN_MESSAGE,
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                null,
                options,
                options[0]
        );
        javax.swing.JDialog dialog = optionPane.createDialog(this, "Create New Account");
        dialog.setVisible(true);

    // Handle user input
        Object selectedValue = optionPane.getValue();
        if (selectedValue != null && selectedValue.equals("Submit")) { // "Submit" button clicked

            String lastName = lastNameField.getText();
            String firstName = firstNameField.getText();
            String middleName = middleNameField.getText();
            String contactNumber = contactField.getText();
            String address = addressField.getText();
            String username = usernameField.getText();
            String password = new String(passwordField.getPassword());
            String confirmPassword = new String(confirmpasswordField.getPassword());
            String role = (String) roleComboBox.getSelectedItem();

            // Validate input
            if (lastName.isEmpty() || firstName.isEmpty() || middleName.isEmpty() || contactNumber.isEmpty() || address.isEmpty() || username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!password.equals(confirmPassword)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(UserMYSQLConnection.getInstance().checkUsernameExist(username)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Username already exists.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

             //  TODO Here you can add code to save the account information to a database or file
            Map<String, Object> userdata = new HashMap<>();
            userdata.put("username", username);
            userdata.put("password", password);
            userdata.put("role", role);
            userdata.put("firstname", firstName);
            userdata.put("lastname", lastName);
            userdata.put("middlename", middleName);
            userdata.put("contactnumber", contactNumber);
            userdata.put("address", address);

            UserMYSQLConnection.getInstance().createAcccount(userdata);
            dialog.dispose(); // Dispose of the dialog
            LoadData();
        } else {
            System.out.println("User canceled the input.");
            dialog.dispose(); // Dispose of the dialog
        }
    }


    // Edit account
    void editAccount() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user to edit.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Retrieve selected user's data from the table
        String currentUsername = (String) jTable1.getValueAt(selectedRow, 1);
        String currentPassword = (String) jTable1.getValueAt(selectedRow, 2);
        String currentRole = (String) jTable1.getValueAt(selectedRow, 3);

        // Create a panel to hold input fields
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.GridLayout(0, 2, 5, 5)); // Grid layout for labels and fields

        // Add input fields with pre-filled data
        panel.add(new javax.swing.JLabel("Username"));
        javax.swing.JTextField usernameField = new javax.swing.JTextField(currentUsername);
        panel.add(usernameField);

        panel.add(new javax.swing.JLabel("Password"));
        javax.swing.JPasswordField passwordField = new javax.swing.JPasswordField(currentPassword);
        panel.add(passwordField);

        panel.add(new javax.swing.JLabel("Confirm Password"));
        javax.swing.JPasswordField confirmpasswordField = new javax.swing.JPasswordField(currentPassword);
        panel.add(confirmpasswordField);

        panel.add(new javax.swing.JLabel("Role"));
        javax.swing.JComboBox<String> roleComboBox = new javax.swing.JComboBox<>(new String[]{"Admin", "User"});
        roleComboBox.setSelectedItem(currentRole);
        panel.add(roleComboBox);

        // Custom button options
        Object[] options = {"Save", "Cancel"};

        // Wrap JOptionPane in a JDialog
        javax.swing.JOptionPane optionPane = new javax.swing.JOptionPane(
                panel,
                javax.swing.JOptionPane.PLAIN_MESSAGE,
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                null,
                options,
                options[0]
        );
        javax.swing.JDialog dialog = optionPane.createDialog(this, "Edit Account");
        dialog.setVisible(true);

        // Handle user input
        Object selectedValue = optionPane.getValue();
        if (selectedValue != null && selectedValue.equals("Save")) { // "Save" button clicked
            String username = usernameField.getText();
            String password = new String(passwordField.getPassword());
            String confirmPassword = new String(confirmpasswordField.getPassword());
            String role = (String) roleComboBox.getSelectedItem();

            // Validate input
            if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!password.equals(confirmPassword)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update the user's data in the database
            try {
                boolean success = UserMYSQLConnection.getInstance().updateAccount(
                        (int) jTable1.getValueAt(selectedRow, 0), // User ID
                        username,
                        password,
                        role
                );

                if (success) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Account updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    LoadData(); // Refresh the table
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to update account.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("User canceled the input.");
            dialog.dispose(); // Dispose of the dialog
        }
    }

    void DeleteAccount(){

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user to delete.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int userId = (int) jTable1.getValueAt(selectedRow, 0); // Assuming the first column is the user ID

        int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this account?", "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
            // Proceed with deletion
            try {
                UserMYSQLConnection.getInstance().deleteAccount(userId);
                javax.swing.JOptionPane.showMessageDialog(this, "Account deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                LoadData(); // Refresh the table
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("User canceled the deletion.");
        }
    }

    void LoadData(){
        userTableModel = (DefaultTableModel) jTable1.getModel();
        userList = UserMYSQLConnection.getInstance().getUser();
        userTableModel.setRowCount(0); // Clear existing rows

        for (UserModel user : userList) {
            Object[] rowData = {
                user.getId(),
                user.getUsername(),
                user.getPassword(),
                user.getRole()
            };
            userTableModel.addRow(rowData);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
